android-pixel-3:
  type: instrumentation
  app: app/build/outputs/apk/debug/app-debug.apk
  test: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
  device:
    - model: Pixel3
      version: 30
      locale: 'en'
      orientation: portrait