name: Development
run-name: Accepting Pull Request to main
on:
  pull_request:
    branches:
      - main
jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
  cancel_previous_workflows:
    name: Cancel Previous Workflows
    needs: ssh
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.11.0
  unit_testing:
    name: Run Unit Tests
    needs: cancel_previous_workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Java Version
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Perform Unit Tests
        run: bash ./gradlew test --stacktrace
  lint:
    name: Run Lint Check
    needs: cancel_previous_workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Java Version
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Grant Permission for Gradlew
        run: chmod +x gradlew
      - name: Perform Gradlew Lint
        run: ./gradlew lint
      - name: Lint Results
        uses: actions/upload-artifact@v1
        with:
          name: lint-results
          path: app/build/reports/lint-results-debug.html
  instrumented_tests:
    name: Run Intrumented Tests
    needs: cancel_previous_workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests on Firebase Test Lab
        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
        with:
          arg-spec: 'tests.yml:android-pixel-4'
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}