name: Pull request
run-name: Accepting pull request
on:
  pull_request:
    branches:
      - staging
jobs:
  cancel_workflows:
    name: Cancel Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.11.0
  QA:
    name: QA
    needs: firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Assemble app debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.SERVICE_ACCOUNT }}
          groups: QA
          file: app/build/outputs/apk/debug/app-debug.apk