name: Staging
run-name: Accepting pull request to staging
on:
  pull_request:
    branches:
      - staging
jobs:
  cancel_previous_workflows:
    name: Cancel Previous Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.11.0
  QA:
    name: Send APK to Quality Assurance
    needs: cancel_previous_workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Setup Java Version
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Assemble App Debug APK
        run: bash ./gradlew assembleRealease --stacktrace
      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.SERVICE_ACCOUNT }}
          groups: QA
          file: app/build/outputs/apk/release/app-release.apk