name: GitHub Actions Demo
run-name: Tests 🚀
on:
  pull_request:
  push:
    branches:
      - main
      - CI/CD
jobs:
  test:
    runs-on: macos-latest # or any other machine
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

        report:
          runs-on: ubuntu-latest
          needs: test # The report job will run after test job
          if: ${{ always() }} # IMPORTANT: Execute report job regardless of status
          steps:
            - name: Download Test Reports Folder
              uses: actions/download-artifact@v2
              with:
                name: reports

            - name: Android Test Report
              uses: asadmansr/android-test-report-action@v1.2.0