name: testing
run-name: Accepting pull request
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Assemble app debug APK
        run: ./gradlew assembleDebug
      - name: Assemble Android Instrumentation Tests
        run: ./gradlew assembleAndroidTest
      - name: Login to Google Cloud
        run: gcloud auth login
      - name: Set up Cloud SDK
        run: gcloud init
      - name: Set current project
        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}
      - name: Run Instrumentation Tests in Firebase Test Lab
        run: gcloud firebase test android run --type instrumentation --app build/outputs/apk/debug/app-debug.apk --test build/outputs/apk/androidTest/debug/app-debug-androidTest.apk