name: testing
run-name: Accepting pull request
on:
  pull_request:
    branches:
      - main
jobs:
  cancel_workflows:
    name: Cancel Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.11.0
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Assemble app debug APK
        run: ./gradlew assembleDebug
      - name: Assemble Android Instrumentation Tests
        run: ./gradlew assembleAndroidTest
      - name: Give permitions
        run: chmod +x build/outputs/apk/debug/app-debug.apk
      - name: Login to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCLOUD_AUTH }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - name: Set current project
        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}
      - name: Run Instrumentation Tests in Firebase Test Lab
        run: gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk