name: GitHub Actions Demo
run-name: Tests 🚀
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: macos-latest # or any other machine
    steps:
      # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
  report:
    runs-on: ubuntu-latest
    needs: test # The report job will run after test job
    if: ${{ always() }} # IMPORTANT: Execute report job regardless of status
    steps:
      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: reports
        run: ./gradlew lint
      - uses: yutailang0119/action-android-lint@v3
        with:
         report-path: build/reports/*.xml
        continue-on-error: true